---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bbdata-operator-acc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-all-ressources
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-all-ressources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-all-ressources
subjects:
  - kind: ServiceAccount
    name: bbdata-operator-acc
    namespace: bbdata-operator

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: bbdata.stable.bukibarak.ch
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.bukibarak.ch
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                defaultReplica:
                  type: integer
                cassandraReplica:
                  type: integer
                kafkaReplica:
                  type: integer
                bbdataReplica:
                  type: integer
                cassandraStorageClass:
                  type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: bbdata
    # singular name to be used as an alias on the CLI and for display
    singular: bbdata
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: BBData
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - ct

---
apiVersion: v1
kind: Pod
metadata:
  name: bbdata-operator
spec:
  containers:
  - name: bbdata-operator
    image: bukibarak/bbdata-operator:v1
    imagePullPolicy: Always
    env:
  serviceAccountName: bbdata-operator-acc