version: "3"
services:
### PROCESSING ###
  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    container_name: bbZooKeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

    ports:
      - '2181:2181'
    networks:
      - bb-processing-network
   
      
  kafka:
    image: 'bitnami/kafka:3'
    restart: always
    container_name: bbKafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    
    ports:
      - '9092:9092'
    networks:
      - bb-processing-network  
    depends_on:
      - zookeeper


  kafka-cli:
    build: './components/kafka-cli/'
    container_name: bbKafka-cli
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - WAIT_HOSTS=zookeeper:2181,kafka:9092

    networks:
      - bb-processing-network
    depends_on:
      - zookeeper
      - kafka

### NETWORKS ###
networks:
  bb-processing-network:
    driver: bridge