apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.0.0
    replicas: KAFKA_REPLICA_SIZE #will be modified by the deployment script
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: KAFKA_REPLICA_SIZE #will be modified by the deployment script
      transaction.state.log.replication.factor: KAFKA_REPLICA_SIZE #will be modified by the deployment script
      transaction.state.log.min.isr: KAFKA_MIN_REPLICA_SIZE #will be modified by the deployment script
      default.replication.factor: KAFKA_REPLICA_SIZE #will be modified by the deployment script
      min.insync.replicas: KAFKA_MIN_REPLICA_SIZE #will be modified by the deployment script
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: KAFKA_REPLICA_SIZE #will be modified by the deployment script
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}