apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - image: bukibarak/bbdata-webapp:latest
          name: nodejs
          env:
            - name: API_SERVER_HOST
              value: http://spring:8080
          ports:
            - containerPort: 8088
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  ports:
    - name: "8088"
      nodePort: 30088
      port: 8088
      targetPort: 8088
  selector:
    app: nodejs
  type: NodePort
