apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  ports:
  - name: "8088"
    nodePort: 30088
    port: 8088
    targetPort: 8088
  selector:
    app: nodejs
  type: LoadBalancer
