apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring
spec:
  ports:
  - name: "8080"
    nodePort: 30080
    port: 8080
    targetPort: 8080
  selector:
    app: spring
  type: LoadBalancer
